0.9.0 changes
aerospike/avs-client-python pull request #35
Opened 2024-07-19 05:56 UTC by DomPeliniAerospike

2024-07-23 00:11 UTC, jdogmcsteezy requested changes
Looks good! Large PRs come with a lot of comments. Keep in mind that I tried to not repeat myself when a comment could apply to both async and sync clients

2024-07-23 00:11 UTC, jdogmcsteezy commented on tests/aerospike-vector-search.yml
> +    #  password-file: aerospike-password.txt
delete the stuff that is not valid. Some of this is from the original confi spec but things have changed. This credentials stanza is replaced by the auth-token stanza above. I just don't want anyone reading these and getting the wrong idea

2024-07-23 00:11 UTC, jdogmcsteezy commented on tests/assets/aerospike-proximus.yml
> +    # Aerospike credentials if required.
remove commented out stuff that is no longer valid. Change the name of this file. Proximus is d34d

2024-07-23 00:11 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/client.py
> +        if not self._channel_provider.client_server_compatible:
why this extra check? Why not just make self._channel_provider.client_server_compatible apart of the _is_ready() logic? The client should not have to know about the inner workings of the provider

2024-07-23 00:11 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/client.py
> +            await self._channel_provider._is_ready()
_is_ready is not private so should not have an underscore

2024-07-23 00:11 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/client.py
> +        timeout: Optional[int] = None,
timeouts could be a timedelta instead

2024-07-23 04:02 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/shared/base_channel_provider.py
> +            self.minimum_required_version
The array is order lexiographic.

For example

`bar`
Comes before
`bare`

and 
`[0, 9, 0]`
comes before
`[0, 9, 0, 'dev1']`

I obviously can't test this without a server, but this logic should be correct

2024-07-23 14:30 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +        index_storage: Optional[types.IndexStorage] = None,
Changed in most recent commits.

2024-07-23 14:33 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +    def add_user(
Added all Docstrings, API Doc's also formatted to look more readable in recent commits

2024-07-23 14:37 UTC, DomPeliniAerospike commented on pyproject.toml
> +    "numpy",
Numpy support in our case is fairly limited (just converting np types to python types), so I think it is relatively safe to not lock the version. Numpy major version 2 is coming soonish, so we may need to review later, but it likely won’t change the mentioned functionality.

2024-07-23 14:43 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +        username: Optional[str] = None,
I think a authentication class and a TLS class might be cleaner and help to document what you need for a full fledged TLS/Auth connection. Factories are a good idea. I should backlog this idea.

2024-07-23 14:43 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +                index_drop_request, credentials=self._channel_provider._token, **kwargs
Added a get_token() function.  I think I will have to take a more base level approach to changing variable names to their correct private and public conventions.  I think I’m a bit confused about what is public and private, because something that isn’t customer facing may technically be public. I likely need to adjust several variables to correctly comply to this convention, so I will backlog this and address this down the line.

2024-07-23 14:43 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +        if timeout is not None:
I moved them to the helpers to cut back on duplicate code in the next commit

2024-07-23 14:44 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +    def get_user(self, *, username: str, timeout: Optional[int] = None) -> int:
Fixed this in recent commits

2024-07-23 14:44 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +    def update_credentials(
Fixed this in recent commits

2024-07-23 14:44 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +                            message="This AVS Client version is only compatbile with AVS Servers above the following version number: "
This statement is actually still true even after new servers come out.  It doesn’t says its compatible with all servers above that, just that it is only compatible with servers above the number.  We can’t just lock the version to a single version because as new server come out, they will likely be backwards compatible. Maybe we could keep a breaking change value in the server and verify that the breaking change number is the same.
TLDR: this should be improved in the future but I think it is suitable for now, I will backlog this idea.

2024-07-23 14:45 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +                    raise types.AVSClientError(
See the above comment.  Also, we can backlog a ticket for an error message object to cut down on all error message duplicate code.

2024-07-23 14:45 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +                    )
I moved some of the duplication to a neutral function.  However, I have to separate stub calls because I must await async stubs, so much of the highlighted code cannot be included in a neutral function.

2024-07-23 14:46 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +
I think we should explore this further and plan some work for a new token_manager implementation.  Personally, I don’t see why tending your auth token wouldn’t be a part of tending your connection.  I do think the token refresh code could be cleaned up, but I’m not sure why it isn’t a tending action.  Tend interval is also not tuneable as of now.

2024-07-23 14:47 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
>          (index_stub, index_create_request) = self._prepare_index_create(
Looked into this one, there is not a way to do this in Python as far as  I could find.  You can provide credentials to the channel, but since we use refresh logic it is not a great fit.

2024-07-23 14:49 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +                certificate_chain = None
This point is true, reconfigured to accept byte encodings instead of a path.

2024-07-23 14:49 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +            if self._private_key:
We are unconcerned about the private_key password, the private_key itself enough verification to use the server.  The private_key is generated using the password, but the password is managed by the server in storepass and keypass values.

2024-07-23 14:49 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/shared/admin_helpers.py
> +                hnsw_params_dict["healer_params"] = healer_params_dict
I am going to backlog this one. A broader idea is a factory for async and sync channels with all options.

2024-07-23 14:50 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +        if self._root_certificate:
I am going to backlog this one. A broader idea is a factory for async and sync channels with all options.

2024-07-23 14:51 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +            print("Failed to refresh authentication token with error: %s", e)
Changed these print statements to logs

2024-07-23 14:51 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/shared/base_channel_provider.py
> +        if self._token and (time.time() - self._ttl_start) > (
Scheduling ttl to refresh is a great idea.  I wish I thought of that earlier.  I will backlog this since it doesn’t seem critical to implement now, but I think it is a solid and simple performance improvement.

2024-07-23 14:52 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/shared/base_channel_provider.py
> +        self._ttl_start = payload["exp"]
This is a bug.  This just forced it to refresh every tend cycle (yikes).  Fixed it by switching _ttl_start to "iat" rather than "exp".

2024-07-23 14:53 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/shared/base_channel_provider.py
> +        if self._token and (time.time() - self._ttl_start) > (
Solved in the comment above.  Should be correctly implemented now.

2024-07-23 14:53 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/shared/helpers.py
> +def _prepare_wait_for_index_waiting(client, namespace, name, wait_interval):
We should discuss this more and possibly backlog a ticket.  I think splitting the clients up into different helper files potentially helps with organization, but I could be convinced to put them in the same place with the right rationale.

2024-07-23 14:54 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +class HnswHealerParams(object):
This would be nice, but it feels like it would be easier just to copy the type hints from the proto files.  If the proto file changes, we will have to update the docstring too, but that will already be one our minds.  If we could automate it quickly and extend its use to other clients, it may be worthwhile.  I can backlog a ticket on this topic.

2024-07-23 14:55 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +    PLACEHOLDER FOR TEXT
I added docstrings, but my link game was admittedly weak.  Once all the new Docs are posted, I can review and add links where necessary.

2024-07-23 14:56 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +        self.expiry = expiry
I will backlog this.  Sounds like a feature that could be user friendly and a good improvement for the future.

2024-07-23 14:56 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
>          self.interval = interval
See above comment.

2024-07-23 14:56 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
>          params.batchingParams.CopyFrom(self.batching_params._to_pb2())
I don’t remember all the details, but I do remember that I was having errors when using dot notation to assign these values directly.  There is an imperative to use CopyFrom to correctly populate the params.

2024-07-23 14:57 UTC, DomPeliniAerospike commented on templates/service.config.json.template
> +### Behaviors
This document is incomplete, I will clean it up in the coming days.

2024-07-23 14:57 UTC, DomPeliniAerospike commented on tests/aerospike-vector-search.yml
> +    #  password-file: aerospike-password.txt
I don’t think this was replaced.  This is the aerospike credentials, not the AVS credentials.  I am fairly sure this is still used if you need password credentials for aerospike.  I haven’t configure a cluster to test this out, but it is certainly a valid scenario.

2024-07-23 14:58 UTC, DomPeliniAerospike commented on tests/assets/aerospike-proximus.yml
> +    # Aerospike credentials if required.
Removed this file, but again, I'm not some of the other parts were removed.

2024-07-23 14:59 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/client.py
> +        if not self._channel_provider.client_server_compatible:
I short circuited on this one.  I was trying to keep the comparison to one at the least case, but forgot to abstract the comparison.  Fixed in recent commits.

2024-07-23 14:59 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/client.py
> +            await self._channel_provider._is_ready()
I commented above about private-public conventions usage needing a deeper review.  WIll address this with that work.

2024-07-23 15:05 UTC, DomPeliniAerospike commented
Responded to all of Jesse's comments, requesting re-review

2024-07-23 15:41 UTC, jdogmcsteezy commented on src/aerospike_vector_search/admin.py
> +                index_drop_request, credentials=self._channel_provider._token, **kwargs
marking something as private is for anyone who interacts with the class. Currently the clients are the only consumers of the connection provider. It tells the developer, "I promise not to break this in the future"

2024-07-23 16:01 UTC, jdogmcsteezy commented
responded

2024-07-23 16:01 UTC, jdogmcsteezy requested changes

2024-07-23 16:32 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +                index_drop_request, credentials=self._channel_provider._token, **kwargs
I get the sense I would want to make a lot more things private if this is the guideline, but some consistentcy is needed.

2024-07-23 16:34 UTC, dwelch-spike commented on src/aerospike_vector_search/admin.py
> +    def list_roles(self, timeout: Optional[int] = None) -> list[str]:
I mostly agree with the "all the types should be defined objects" comment here. In the base Aerospike client using native types like dictionaries as return types has led to lots of usability and maintenance issues. If all an API will ever do is return a collection of strings, then a list of strings makes sense, but if it returns/could return any data type with multiple fields like tuples or dictionaries they should be defined objects.

I suggest returning a list of role objects here.

2024-07-23 16:34 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +
Setting a timer for the reset interval is a great approach.  We will implement this in the near future.

2024-07-23 16:39 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
>          (index_stub, index_create_request) = self._prepare_index_create(
We could probably use the seed_channels to call authservice and do this, but we would also need open new channels to refresh the token for the channel everytime is expires.  I am not sure you can do this on the fly without opening a new connection.

2024-07-23 16:55 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/shared/base_channel_provider.py
> +            self.minimum_required_version
Fixing this in next commit

2024-07-23 16:58 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +    PLACEHOLDER FOR TEXT
I can update the Docs without doing a release, so I won't let this block, but I can spend some time soon sprinkling in the knowledge.

2024-07-23 17:06 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +    def list_roles(self, timeout: Optional[int] = None) -> list[str]:
We just return all the roles object in a list.  We should add custom typing for this in a future release.

Added the type hint in the next commits.

2024-07-23 17:08 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +class HnswHealerParams(object):
They are present in types.py.

2024-07-23 18:54 UTC, jdogmcsteezy reviewed
I don't see any changes to the returned value. Did it already return a dict?

2024-07-23 20:52 UTC, dwelch-spike reviewed
Non-blocking: Review of docstrings. Looks good, some comments and nitpicks

2024-07-23 20:52 UTC, dwelch-spike commented on src/aerospike_vector_search/aio/client.py
> +    :param seeds: Defines the Aerospike Database cluster nodes to which you want AVS to connect. AVS iterates through the seed nodes. After connecting to a node, AVS discovers all of the nodes in the
Are these seeds for Aerospike or AVS? I thought the client would be connecting to AVS.

2024-07-23 20:52 UTC, dwelch-spike commented on src/aerospike_vector_search/aio/client.py
> +            and later, the index healer would pick for indexing. Defaults to False.
```suggestion
        :param ignore_mem_queue_full: Ignore the in-memory queue full error. These records will be written to storage
            and later, the index healer will pick them for indexing. Defaults to False.
```

2024-07-23 20:52 UTC, dwelch-spike commented on src/aerospike_vector_search/aio/client.py
> +        :type dimensions: int
Same comment as above "would" -> "will"

2024-07-23 20:52 UTC, dwelch-spike commented on src/aerospike_vector_search/client.py
> +    :type seeds: Union[types.HostPort, tuple[types.HostPort, ...]]
Are these AVS or Aerospike nodes being connected to?

2024-07-23 20:52 UTC, dwelch-spike commented on src/aerospike_vector_search/client.py
> +    :type private_key: Optional[bytes]
Switched doc strings?

2024-07-23 20:52 UTC, dwelch-spike commented on src/aerospike_vector_search/client.py
> +            and later, the index healer would pick for indexing. Defaults to False.
Same comment as before, I think would -> will makes sense.

2024-07-23 20:52 UTC, dwelch-spike commented on src/aerospike_vector_search/client.py
> +        :type dimensions: int
would -> will, I'm going to stop marking these

2024-07-23 20:52 UTC, dwelch-spike commented on src/aerospike_vector_search/client.py
> +            AVSServerError: Raised if an error occurs during the RPC communication with the server while attempting to create the index.
```suggestion
            AVSServerError: Raised if an error occurs during the RPC communication with the server while attempting to delete the record.
```

2024-07-23 20:52 UTC, dwelch-spike commented on src/aerospike_vector_search/client.py
> +            AVSServerError: Raised if an error occurs during the RPC communication with the server while attempting to create the index.
```suggestion
            AVSServerError: Raised if an error occurs during the RPC communication with the server while attempting to wait for the index.
```

I think there are more of these that I missed.

2024-07-24 13:20 UTC, DomPeliniAerospike commented
I will adresss Dylan's review comments after release

2024-07-24 13:20 UTC, merged

2024-08-06 14:59 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +    :type private_key: Optional[bytes]
Fixed in latest release.

2024-08-06 15:00 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +        :param index_params: (Optional[types.HnswParams], optional): Parameters used for tuning
Fixed in latest release.

2024-08-06 15:00 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +            AVSServerError: Raised if an error occurs during the RPC communication with the server while attempting to drop the index..
Fixed all double period in latest release.

2024-08-06 15:00 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +        :param password: New password for the userr.
Fixed in latest release

2024-08-06 15:25 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/client.py
> +            AVSServerError: Raised if an error occurs during the RPC communication with the server while attempting to create the index.
Addressed mislabelled error messages in latest release.

2024-08-06 15:25 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/client.py
> +        :type dimensions: int
Addressed in most recent release.

2024-08-06 15:25 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/client.py
> +            and later, the index healer would pick for indexing. Defaults to False.
Addressed in most recent release.

2024-08-06 15:25 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/client.py
> +    :type seeds: Union[types.HostPort, tuple[types.HostPort, ...]]
AVS nodes.   Addressed in most recent release.

2024-08-06 15:26 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/client.py
> +        :type dimensions: int
Addressed in most recent release.

2024-08-06 15:26 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/client.py
> +            and later, the index healer would pick for indexing. Defaults to False.
Addressed in most recent release.

2024-08-06 15:26 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/client.py
> +    :param seeds: Defines the Aerospike Database cluster nodes to which you want AVS to connect. AVS iterates through the seed nodes. After connecting to a node, AVS discovers all of the nodes in the
AVS nodes. Addressed in most recent release..

2024-08-06 15:26 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/admin.py
> +        grant roles to existing AVS Users.
Addressed in most recent release.

2024-08-06 15:26 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/admin.py
> +        :param roles: Roles the specified user will no longer maintain..
Addressed in most recent release.

2024-08-06 15:26 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/admin.py
> +        grant roles to existing AVS Users.
Addressed in most recent release.

2024-08-06 15:26 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/admin.py
> +        Retrieves AVS User information from the AVS Server
Addressed in most recent release.

2024-08-06 15:26 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/admin.py
> +        :param password: New password for the userr.
Addressed in most recent release.

2024-08-06 15:26 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/admin.py
> +    :type private_key: Optional[bytes]
Addressed in most recent release.

2024-08-06 15:27 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +        grant roles to existing AVS Users.
Addressed in most recent release.

2024-08-06 15:27 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +        Retrieves AVS User information from the AVS Server
Addressed in most recent release.

2024-08-06 15:27 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/admin.py
> +        :param password: New password for the userr.
Addressed in most recent release.

2024-08-06 15:27 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/client.py
> +    :type private_key: Optional[bytes]
Addressed in most recent release.