AVS Python Client Release 1.0.1
aerospike/avs-client-python pull request #39
Opened 2024-08-02 17:20 UTC by DomPeliniAerospike

2024-08-02 23:07 UTC, dwelch-spike reviewed
I'm new to this project so I had some understanding questions and probably some comments that don't make sense, feel free to disagree with me 😆 . I think using type hints on all the function definitions would be good and I left a few other comments you should look at. Nice job! When you have had a look I will give it a thumbs up.

2024-08-05 16:05 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +        # When set, client has completed a cluster tend cycle, initialized auth, and
Completed commented in next commit

2024-08-05 16:18 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            await asyncio.sleep(1)
This should be configurable, but I will just set a constant for now since I'm not sure if that is an approved feature by Adam.

2024-08-05 16:26 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            elif self._token != True:
self._token is true when credentials have been provided, but the token has not been received from the server.  When set, it will be an object and not a bool.

2024-08-05 16:26 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +                pass
This should still be safe, but its not optimal. I added this before I added the try except block wrapping all the code in the function, and this should avoid throwing the error, which is the behavior I wanted.  Nice catch!

2024-08-05 16:27 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +        self._auth_tending: asyncio.Lock = asyncio.Lock()
Made the change in next commit.

2024-08-05 16:29 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            raise e
The logs fire inside the inner function, so I didn't think it was necessary, but it could be helpful.  I will add a message. More detail probably can't hurt.

2024-08-05 16:32 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +    ) -> None:
I have the public facing API's covered completely, but I was less concerned about private functions.  This would be a good improvement, especially if someone else had to start developing on the python client.  This will have to be addressed in a Jira and future work.

2024-08-05 16:35 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            raise types.AVSServerError(rpc_error=e)
If another exception type is raised, it will be handled by _tend_token an assigned to the _tend_exception which is thrown before API calls are executed if present.

2024-08-05 16:36 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +        self._auth_tending: threading.Lock = threading.Lock()
Changed in next commit.

2024-08-05 16:45 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            self._tend_exception = e
Added this log.

2024-08-05 16:48 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
>          self._timer = None
Changed this in next commit.

2024-08-05 16:48 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +    ) -> None:
Addressed this in earlier comment.

2024-08-05 16:52 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +        self._respond_authenticate(response.token)
I don't want to wrap any other error type because those are just exceptions.  AVS errors wrap RpcErrors.  If their is an unexpected failure (non RpcError), it should just raise the exception and fail with a fatal error.  It will provide error info in this case, and that should be sufficient.

2024-08-05 16:53 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +            self._tend_exception = AVSServerError(rpc_error=e)
This should be raise instead, nice catch, thank you!

2024-08-05 16:57 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +            self._timer.join()
I guess it's just two ways to crack an egg. This just makes sure it has drained, which it probably should anyways since there is a lock that is only unlocked right before returning.  I don't think it hurts anything so I just left it in to be sure the thread ends correctly.

2024-08-05 16:58 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/shared/base_channel_provider.py
> +                # TODO: Wait for all calls to drain
I think this probably addressed, but I need to formally address this with a Jira and an investigation.

2024-08-05 17:00 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/shared/base_channel_provider.py
> +        # TODO: Worry about thread safety
This needs to be formally investigated before removing.  Will address in the future.

2024-08-05 17:46 UTC, dwelch-spike commented on src/aerospike_vector_search/internal/channel_provider.py
> +        self._auth_tending_lock: threading.Lock = threading.Lock()
I think the async version of this should also include "lock" in the name.

2024-08-05 18:47 UTC, jdogmcsteezy requested changes

2024-08-05 18:47 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +        self._task: Optional[asyncio.Task] = asyncio.create_task(self._tend())
_task is not descriptive enough

2024-08-05 18:47 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +        self._auth_tending: asyncio.Lock = asyncio.Lock()
Why would multiple tasks be assigned?

2024-08-05 18:47 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            self._task = asyncio.create_task(self._tend_cluster())
self._task is being assigned self._tend_cluster() here but above it it assigned self._tend(). Is that on purpose?

2024-08-05 18:47 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            await self._auth_task
I see this in self._auth_task

```
await asyncio.sleep((self._ttl * self._ttl_threshold))
```

self._tend_cluster() has it's own sleep interval. Why are we synchronizing them both here?

2024-08-05 18:47 UTC, jdogmcsteezy commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            await self._auth_task
Another question, why are we not using an event to communicate that auth is finished?

2024-08-05 19:01 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/internal/channel_provider.py
> +        self._auth_tending_lock: threading.Lock = threading.Lock()
Nice catch, I thought I made this change, but I guess I forgot to save.  Will be in next commit.

2024-08-05 22:54 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +                await asyncio.gather(*tasks)
Yes, this is sort of what I was talking about in the meeting by using an async channel and capturing the result in a task.

2024-08-05 22:55 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            await self._update_token_and_ttl()
I have no testing for this, maybe we have some logic to try all the seed nodes in here?  I'll note it and move to backlog.

2024-08-05 22:56 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +        self._task: Optional[asyncio.Task] = asyncio.create_task(self._tend())
Changed to tend_task

2024-08-05 23:04 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +        self._auth_tending: asyncio.Lock = asyncio.Lock()
If the token refreshes, and new task is assigned.

2024-08-06 14:41 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            await self._auth_task
1. I'm not sure what synchronization you are referencing.  I separated the auth tending and cluster tending into sub functions rather than having 1 tend function.  There is still a tend function, but it just initializes all the tending sub-functions and returns.  The intended behavior should mimic a threading.timer in an async way.
2. We aren't using an event because we are cancelling the task.  Since it is a long running task, we need to interrupt it.  We use a lock to keep a valid reference to the current task, and then cancel the task.  An event works better for the cluster tending because this job is constantly being refreshed, but since the minimum token expirary is around 1 day, the current approach is more valid in my opinion.

2024-08-06 14:42 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            self._task = asyncio.create_task(self._tend_cluster())
I removed the tracking for this task, it is unnecessary due to the event which signals the end of tending.

2024-08-06 14:54 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            logger.error("Unexpected tend failure: %s", e)
We should maybe huddle on this.  In my mind, this failure signals a connection failure and is a valid fatal exception, similar to auth failure.  I'd like to hear your perspective.

2024-08-06 16:11 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            elif self._token != True:
I will log a ticket to change this to check for self._credentials, but I don't think it is critical/blocking for this release.

2024-08-06 16:11 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +        self._task: Optional[asyncio.Task] = asyncio.create_task(self._tend())
Removed this entirely.

2024-08-06 17:56 UTC, jdogmcsteezy approved these changes
Approving with the caveat that some things will be fixed/investigated in the future.

1. Better coverage for seed nodes which are not all accessible to the client
2. Rename tend_ to something like init_tend or init_cluster_tend 
3. Investigate whether the auth lock is needed

2024-08-06 18:02 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            logger.error("Unexpected tend failure: %s", e)
Work arounds:
Maybe logging a warning might be better, 
Multiple stubs
parameter to ignore the version

2024-08-06 18:04 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/internal/channel_provider.py
> +            await self._update_token_and_ttl()
Tend interval needs changes to auth_tend task tracking if we make this configurable.

2024-08-06 18:23 UTC, merged