feat: vec-327 add field_exclusions optional parameter to client.get a…
aerospike/avs-client-python pull request #51
Opened 2024-09-21 00:03 UTC by dwelch-spike

…nd client.vector_search() to filer out fields returned by the AVS server

2024-09-26 15:04 UTC, DomPeliniAerospike requested changes
Left some small comments and questions, but overall it looks great!  Let me know when you address the comments, and I will come back around to approve.

2024-09-26 15:04 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +        if not isinstance(other, Neighbor):
Should we allow people to compare non-class object to a neighbor?  I could see a scenario where they just create the object in line rather than importing our types package and instantiating a neighbor.

2024-09-26 15:04 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +        if not isinstance(other, Key):
See note below about comparing non-class objects.

2024-09-26 17:29 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +    def __eq__(self, other) -> bool:
I needed this to do comparisons in the vector_search test suite. We should slowly fill out the other ones. It would be nice to have them defined automatically by the dataclass decorator or something. Something to look into in the future

2024-09-26 17:29 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +from dataclasses import dataclass
Good catch, this is from something I tried out that didn't work. I was hoping decorating some of these types with DataClass would give us magic methods like __eq__ and __str__ for free, but the __eq__ method didn't work as expected.

2024-09-26 17:30 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +from dataclasses import dataclass
Removed the import

2024-09-26 17:30 UTC, dwelch-spike commented on src/aerospike_vector_search/client.py
> +            saving on network traffic.
done

2024-09-26 17:30 UTC, dwelch-spike commented on src/aerospike_vector_search/client.py
> +            If None, all fields are retrieved. Defaults to None.
done

2024-09-26 17:30 UTC, dwelch-spike commented on src/aerospike_vector_search/aio/client.py
> +            saving on network traffic.
done

2024-09-26 17:30 UTC, dwelch-spike commented on src/aerospike_vector_search/aio/client.py
> +            warnings.warn(
warning.warn seems to be standard for cases where the user application is doing something ill advised by choice (in this case, using deprecated functionality) source: https://docs.python.org/3/howto/logging.html#when-to-use-logging

I also see it used in the pinecone https://github.com/search?q=repo%3Apinecone-io%2Fpinecone-python-client%20warnings.warn&type=code . Although they use FutureWarning, which is visible by default. I will switch to use that.

2024-09-26 17:30 UTC, dwelch-spike commented on src/aerospike_vector_search/aio/client.py
> +            saving on network traffic.
Done, added...
```
            If a field is listed in both include_fields and exclude_fields,
            exclude_fields takes priority, and the field is not returned.
```

2024-09-26 17:37 UTC, dwelch-spike commented on tests/standard/aio/test_vector_search.py
> +class get_test_case:
done

2024-09-26 17:37 UTC, dwelch-spike commented on tests/standard/sync/test_vector_search.py
> +class get_test_case:
done

2024-09-26 17:45 UTC, dwelch-spike commented on tests/standard/aio/test_vector_search.py
> +                        set="", #TODO should this accept None?
Should the type hints for set change? They are this currently
```
    def __init__(self, *, namespace: str, set: str, key: Any) -> None:
        self.namespace = namespace
        self.set = set
        self.key = key
```
Seems like they should be
```
    def __init__(self, *, namespace: str, set: Optional[str] = None, key: Any) -> None:
        self.namespace = namespace
        self.set = set
        self.key = key
```

2024-09-26 17:45 UTC, dwelch-spike commented on tests/standard/sync/test_vector_search.py
> +                        set="", #TODO should this accept None?
See comment above

2024-09-26 18:44 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +        if not isinstance(other, Neighbor):
IMO we should check the type, atleast for now. I think it's more explicit, an object of another type isn't really "equal" even if it has the same member values, for example, you shouldn't pass it into any of the client APIs

2024-09-26 18:44 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +        if not isinstance(other, Key):
see above

2024-09-26 19:03 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/client.py
> +            warnings.warn(
Okay, I understand the distinction, thank you for linking those resources.

2024-09-26 19:17 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +    def __eq__(self, other) -> bool:
Not very familiar with dataclass, but I agree that using this decorator to add some magic methods could help reduce the verbosity as opposed to defining each one.  As long as a custom method isn't required (Like printing a specially formatted version of the neighbor class for clarify), it would be great to use this where possible.  In the future.

2024-09-26 20:05 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +        if not isinstance(other, Neighbor):
I think its fine to leave for now, but I do think there is merit to also supporting loose equality.

> I think it's more explicit, an object of another type isn't really "equal" even if it has the same member values

Even if its isn't strictly equal since its not a class object, for all intents and purposes, an object with the same properties and values is still loosely equal. Python doesn't have a notation strict equality support (like `===` and `==`) in javascript, so I don't think strict equality is required by convention.

> for example, you shouldn't pass it into any of the client APIs

No API's accept `types.Key` as a value, they all accept `namespace`, `set`, and `key` as different variables, so there is no worry about accidentally passing it into the API.  It is simply a return type used to clearly define which variables will be returned.  Once the object is returned, there is no longer a use for the class since no methods (aside from magic methods) are defined.

I don't see a downside, but I also have a Javascript bias, so I may be overlooking some details.  I just know that a Javascript user would expect loose equality between a class and object with the same properties and values to be true.  Python is strongly-typed, so I can sort of see why strict equality would make sense, but comparing `"1"` and `1` is quite different then comparing two object with identical properties and values.

No action needed, just interested in your thought on this.

2024-09-26 20:10 UTC, DomPeliniAerospike commented on tests/standard/aio/test_vector_search.py
> +                        set="", #TODO should this accept None?
If we switch the typehints, we will have to modify following function to replace "" with None:
```
def fromVectorDbKey(key: types_pb2.Key) -> types.Key:
    keyValue = None
    if key.HasField("stringValue"):
        keyValue = key.stringValue
    elif key.HasField("intValue"):
        keyValue = key.intValue
    elif key.HasField("longValue"):
        keyValue = key.longValue
    elif key.HasField("bytesValue"):
        keyValue = key.bytesValue

    # add the following lines!
    if key.set == "":
        key.set = None
    # add the above lines!
    
    
    return types.Key(namespace=key.namespace, set=key.set, key=keyValue)
```

Without this addition, the new type hint would be incorrect.

2024-09-26 20:11 UTC, DomPeliniAerospike commented on tests/standard/sync/test_vector_search.py
> +                        set="", #TODO should this accept None?
Left a comment above which addresses this. Resolving here.

2024-09-26 20:14 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +from dataclasses import dataclass
Okay, good thought though! Free is always good if possible.

2024-09-26 20:16 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/shared/client_helpers.py
> +                type=transact_pb2.ProjectionType.SPECIFIED, fields=exclude_include_fields
Awesome, great catch with the exclude_include_fields, that one slipped past me.

2024-09-26 20:17 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +        if not isinstance(other, Key):
See note above about loose equality.

2024-09-26 22:30 UTC, dwelch-spike commented on tests/standard/aio/test_vector_search.py
> +                        set="", #TODO should this accept None?
Ok I see what you mean, "" is sent by the server and needs to be converted to None. I think in that case just the docs need to change. set is marked as optional in the docs which normally means it can be None, I think that word should be removed.
```
    """
    Represents a record key.
    Used in RecordWithKey.

    :param namespace (str): The namespace for the key.
    :type namespace: str

    :param set: (optional[str]): The set for the key.
    :type set: optional[str]

    :param key: (Any): The key itself.
    :type key: Union[int, str, bytes, bytearray, np.ndarray, np.generic]

    """
```
to
```
    """
    Represents a record key.
    Used in RecordWithKey.

    :param namespace (str): The namespace for the key.
    :type namespace: str

    :param set: str: The set for the key. Use the empty string "" to signify no set.
    :type set: str

    :param key: (Any): The key itself.
    :type key: Union[int, str, bytes, bytearray, np.ndarray, np.generic]

    """
```
What do you think?

2024-09-26 22:48 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +        if not isinstance(other, Neighbor):
Got it, I see your point, especially knowing that no APIs accept this object. To be honest I'm not sure how normal it is for someone to define some object and compare it to one of another type. The user could always define the __eq__ method of their type so that it works. If anyone ever asks for it I'd consider adding it.

2024-09-27 13:52 UTC, DomPeliniAerospike commented on tests/standard/aio/test_vector_search.py
> +                        set="", #TODO should this accept None?
This lines up with my understanding of the current behavior. Looks good to me.

2024-09-27 13:54 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +        if not isinstance(other, Neighbor):
Okay, upon request sounds good to me, throwing not implemented is definitely suitable for now.

2024-09-27 13:57 UTC, DomPeliniAerospike approved these changes
All my comments have been sufficiently addressed and new changes look good.  Approving now! Great work!

2024-09-27 17:32 UTC, merged