feat: Add vector_search_by_key method to sync and async clients vec-330
aerospike/avs-client-python pull request #53
Opened 2024-10-02 00:55 UTC by dwelch-spike

This feature is a convenience method that enables HNSW searches by Aerospike record primary key instead of by literal vectors. The client does this by reaching out to AVS to get the vector data for the record the user wishes to search on. Some extra arguments are required for this search, namely the record set name and the vector field name.

2024-10-10 21:10 UTC, dwelch-spike commented on src/aerospike_vector_search/aio/client.py
> +        set_name: Optional[str] = None,
Should this be called "key_set" to be consistent with other arguments? Is it easier to understand that this is the set the record resides in if it is called "key_set"?

2024-10-11 00:58 UTC, DomPeliniAerospike requested changes
Left some questions and comments.  Looked good otherwise!

2024-10-11 00:58 UTC, DomPeliniAerospike commented on tests/standard/sync/test_vector_client_search_by_key.py
> +    assert list.sort(results) == list.sort(test_case.expected_results)
Comment: Odd that the server doesn't return this in order, but I guess that isn't how the KNN algorithm works.  I suppose it is a tad faster to send unsorted.

2024-10-11 00:58 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +        return self.distance >= other.distance
This implementation will lead to inconsistent sorting for records that are equal in distance.  Consider the example:

`neighbor1.distance = 4, neighbor2.distance = 4, neighbor3.distance = 0`

`array1 = [neighbor1, neighbor2, neighbor3]`

`array2 = [neighbor2, neighbor1, neighbor3]`

the outcome of `list.sort(array1)` will equal: `[neighbor3, neighbor1, neighbor2,]`

the outcome of `list.sort(array2)` will equal: `[neighbor3, neighbor2, neighbor1,]`

This is due to the python list.sort being a stable sort implementation: [See documentation here](https://docs.python.org/3/howto/sorting.html#sort-stability-and-complex-sorts)

If a user is sorting, they likely want a consistent output, and the current implementation won't provide that.

Sorting a key name in the event of distance equality will solve this issue.

It won't affect most, but the current behavior is sub-optimal for some use cases.

Let me know what you think.

2024-10-11 00:58 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/client.py
> +            namespace=index_namespace,
Are you sure we want to search the `index_namespace` rather than the `key_namespace`?

Doesn't the `index_namespace` just have index info on it, while `key_namespace` has all the records?

A test case should be added to verify that this behavior is sound.  All test cases use the same value for both `key_namespace` and `index_namespace`.

2024-10-11 00:58 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/aio/client.py
> +        set_name: Optional[str] = None,
I think namespace and set should be consistent, they are both key information and should be uniform.  Was never a fan of the "set_name" choice.

Instead of `index_namespace`, it should be `search_namespace`.  This way, it is clear that you find the key in `key_namespace`, and you search in `search_namespace`.  `Index_namespace` could mean where the index information is stored rather than where the vector data is stored.

2024-10-11 00:58 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/client.py
> +            namespace=index_namespace,
I left this comment before leaving the one above. I understand that you might search a different namespace than the one you found the key in.  Changing `index_namespace` to `search_namespace` could clear up the confusion.

A valid test case should still be added for this situation.

2024-10-11 16:55 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +        return self.distance >= other.distance
Good point. I added your suggestion. The key is compared if distances are the same

2024-10-11 17:10 UTC, dwelch-spike commented on src/aerospike_vector_search/aio/client.py
> +        set_name: Optional[str] = None,
Good feedback, these make sense to me. Changed

2024-10-11 17:13 UTC, dwelch-spike commented on src/aerospike_vector_search/client.py
> +            namespace=index_namespace,
renamed `index_namespace` to `search_namespace` I'll see about the test case. I think I'll have to add another namespace to the test Aerospike configs etc

2024-10-11 17:16 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +        return self.distance >= other.distance
We have a problem... comparing keys of different types fails

2024-10-11 19:15 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +        return self.distance >= other.distance
I settled on using the set and string representation of the keys to tie break, let me know what you think

2024-10-11 22:07 UTC, dwelch-spike commented on src/aerospike_vector_search/client.py
> +            namespace=index_namespace,
Added a test case where the record and searchspace are in separate namespaces

2024-10-11 22:12 UTC, dwelch-spike commented on tests/standard/sync/test_vector_client_search_by_key.py
> +    assert list.sort(results) == list.sort(test_case.expected_results)
This posed problems for me when testing but it could have been that my test case data was in a different order. Either way I think being able to sort neighbors is useful.

2024-10-14 17:39 UTC, dwelch-spike commented
@DomPeliniAerospike Turns out that AVS does return sorted results, confirmed by Adam. There was another problem that was causing the tests to fail. I removed the sorting code.

2024-10-14 18:10 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +        return self.distance >= other.distance
Fine solution even if it was removed.

2024-10-14 18:22 UTC, DomPeliniAerospike approved these changes
All my questions have be address in a satisfactory manor.  Approving this pull request!
Well done!

2024-10-14 18:29 UTC, hev approved these changes
LGTM.

2024-10-14 18:34 UTC, merged