Branch 3.0.0 v1
aerospike/avs-client-python pull request #57
Opened 2024-10-17 23:22 UTC by rahul-aerospike

https://aerospike.atlassian.net/browse/VEC-398

2024-10-18 17:05 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +        storage: Optional[IndexStorage] = None,
Why was this change made? Because all the fields of indexStorage are optional? Are you sure that means passing None as IndexStorage works? I think a test case for this would be good.

2024-10-18 17:35 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +        return result
In the client these conversions are done by helper methods in conversions.py. Take for example `fromIndexDefintion`. I think this should be moved there.

2024-10-21 19:14 UTC, rahul-aerospike commented on src/aerospike_vector_search/types.py
> +        return result
@dwelch-spike 
I think we should keep all the functionalities of the class within the class ( if the wrapper class is defined). Let me know if you disagree then I will put the changes in the `conversions.py`.

2024-10-21 19:29 UTC, rahul-aerospike commented on src/aerospike_vector_search/types.py
> +        storage: Optional[IndexStorage] = None,
```
message IndexDefinition {
  // The index identifier.
  IndexId id = 1;

  // The type of index. Defaults to HNSW.
  optional IndexType type = 2;

  // Number of dimensions in data.
  // Vectors not matching the dimension count will not be indexed.
  uint32 dimensions = 3;

  // Optional The distance metric to use. Defaults to SQUARED_EUCLIDEAN.
  optional VectorDistanceMetric vectorDistanceMetric = 4;

  // Name of the record vector field to index.
  string field = 5;

  // Optional filter on Aerospike set name from which records will be indexed.
  // If not specified all sets in the index namespace will be indexed.
  optional string setFilter = 6;

  // Index parameters.
  oneof params {
    HnswParams hnswParams = 7;
  }

  // Optional labels associated with the index.
  map<string, string> labels = 8;

  // Index storage.
  optional IndexStorage storage = 9;
}
```
Proto file says this field should be optional. I'll add some test around it.

2024-10-21 21:01 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +        return result
I think we should keep the conversion functionality consistent in conversions.py.

2024-10-21 21:13 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +        storage: Optional[IndexStorage] = None,
I missed that this was defined as optional, so this makes sense. I don't think a new test case is needed here.

2024-10-21 21:52 UTC, rahul-aerospike commented on src/aerospike_vector_search/types.py
> +        storage: Optional[IndexStorage] = None,
I checked that we have lot of tests where this flag is not set, so essentially we are passing the None. So tests are covered.

2024-10-22 18:25 UTC, rahul-aerospike commented on src/aerospike_vector_search/types.py
> +        return result
done.

2024-10-22 18:28 UTC, rahul-aerospike commented on src/aerospike_vector_search/aio/admin.py
> +        return IndexStatusResponse.from_proto_response(response)
done.

2024-10-22 18:28 UTC, rahul-aerospike commented on src/aerospike_vector_search/admin.py
> +        return types.IndexStatusResponse.from_proto_response(response)
done.

2024-10-22 20:32 UTC, dwelch-spike requested changes
A few more comments.

I think tests should be added for
- setting enableVectorIntegrityCheck

2024-10-22 20:32 UTC, dwelch-spike commented on requirements.txt
> +alabaster==1.0.0
Where do these requirements come from? Is this file needed? Can't you install the project's requirements with `pip install .`?

2024-10-22 20:32 UTC, dwelch-spike commented on src/aerospike_vector_search/aio/admin.py
> +from ..types import IndexStatusResponse
Only `from .. import types` or `from ..types import IndexStatusResponse` is needed. I prefer `from .. import types`

2024-10-22 20:32 UTC, dwelch-spike commented on src/aerospike_vector_search/aio/admin.py
> +from http.client import responses
Is this http import needed?

2024-10-22 20:32 UTC, dwelch-spike commented on src/aerospike_vector_search/aio/admin.py
> -        return self._respond_index_get_status(response)
I think `_respond_index_get_status` is now unused and can be removed.

2024-10-22 20:32 UTC, dwelch-spike commented on src/aerospike_vector_search/shared/conversions.py
> +def fromIndexStatusResponse(response: 'index_pb2.IndexStatusResponse') -> 'IndexStatusResponse':
Why are the type hints in quotes? I think they should be the actual types.

2024-10-22 20:57 UTC, rahul-aerospike commented on requirements.txt
> +alabaster==1.0.0
This should not be here. Removing.

2024-10-22 23:33 UTC, rahul-aerospike commented on src/aerospike_vector_search/shared/conversions.py
> +def fromIndexStatusResponse(response: 'index_pb2.IndexStatusResponse') -> 'IndexStatusResponse':
On the left side, it is needed because it has two words into it.  Removed the quotes from the right side.

2024-10-22 23:34 UTC, rahul-aerospike commented on src/aerospike_vector_search/aio/admin.py
> +from http.client import responses
No. Removed.

2024-10-22 23:34 UTC, rahul-aerospike commented on src/aerospike_vector_search/aio/admin.py
> -        return self._respond_index_get_status(response)
Good catch. Removed.

2024-10-22 23:35 UTC, rahul-aerospike commented on src/aerospike_vector_search/aio/admin.py
> +from ..types import IndexStatusResponse
Removed.

2024-10-22 23:36 UTC, rahul-aerospike commented
> A few more comments.
> 
> I think tests should be added for
> 
> * setting enableVectorIntegrityCheck

Added the tests for enableVectorIntegrityCheck. Non default case is not working. Could be changed back when server fix is available.

2024-10-23 00:06 UTC, dwelch-spike approved these changes
LGTM! Thanks Rahul!

Note: current test failures look like timing issues to me. I think it is OK to merge this.

2024-10-23 00:08 UTC, merged