Test intermediate changes in CI
aerospike/avs-client-python pull request #63
Opened 2024-11-05 04:40 UTC by rahul-aerospike

2024-11-07 00:47 UTC, arrowplum reviewed
visually looks good but I wasn't able to get python type hints in my editor so I will leave it to someone else to approve.

2024-11-07 00:47 UTC, arrowplum commented
Also I see there are some broken tests

2024-11-08 16:58 UTC, dwelch-spike requested changes
I left a few comments to double check things. I also pulled this branch into my IDE and went through some files with PyLance to see if it highlights any type hint issues. It looks much better but still has some. I included a photo of an example. @rahul-aerospike can you install the pylance extension in vscode and take a look? If you can't get it to work let me know and I can make the changes on my side.


<img width="913" alt="image" src="https://github.com/user-attachments/assets/99f42634-85d3-40ff-b263-1ea894b74faf">

2024-11-08 16:58 UTC, dwelch-spike commented on src/aerospike_vector_search/shared/client_helpers.py
> +        record_data: Dict[str, Any],
Seems like `typing.Dict` and `dict` usage is mixed, we should settle one 1, I'd prefer `dict`.

2024-11-08 16:58 UTC, dwelch-spike commented on src/aerospike_vector_search/shared/client_helpers.py
> +    ) -> tuple[transact_pb2_grpc.TransactServiceStub, transact_pb2.PutRequest, dict[str, Any]]:
Checking that transact_pb2.PutRequest is correct and that there isn't an UpsertRequest.

2024-11-08 16:58 UTC, dwelch-spike commented on src/aerospike_vector_search/shared/client_helpers.py
> +    ) -> tuple[transact_pb2_grpc.TransactServiceStub, transact_pb2.PutRequest, dict[str, Any]]:
Double checking that PutRequest is correct.

2024-11-08 16:58 UTC, dwelch-spike commented on src/aerospike_vector_search/shared/client_helpers.py
> +    ) -> tuple[transact_pb2_grpc.TransactServiceStub, transact_pb2.PutRequest, dict[str, Any]]:
Double checking that PutRequest is correct.

2024-11-08 16:58 UTC, dwelch-spike commented on src/aerospike_vector_search/shared/client_helpers.py
> +    ) -> tuple[transact_pb2_grpc.TransactServiceStub, Any, dict[str, Any]]:
Is `Any` correct here or is there a more specific return type that can be used?

2024-11-08 16:58 UTC, dwelch-spike commented on src/aerospike_vector_search/shared/client_helpers.py
> +        Tuple)[index_pb2_grpc.IndexServiceStub, float, float, bool, int, index_pb2.IndexGetRequest]:
Double checking that IndexGetRequest is right here and there isn't a IndexWaitRequest.

2024-11-13 21:10 UTC, rahul-aerospike commented on src/aerospike_vector_search/shared/admin_helpers.py
> +    def _prepare_list_roles(self, timeout: Optional[int], logger: logging.Logger) -> tuple[user_admin_pb2_grpc.UserAdminServiceStub, Any, dict[str, Any]]:
The 2nd field is 
       `list_roles_request = empty` where `empty = google.protobuf.empty_pb2.Empty()`. So i'm not quite sure what should be type here.

2024-11-13 21:15 UTC, rahul-aerospike commented on src/aerospike_vector_search/shared/client_helpers.py
> +    ) -> tuple[transact_pb2_grpc.TransactServiceStub, transact_pb2.PutRequest, dict[str, Any]]:
@dwelch-spike  2nd field is 
`put_request = transact_pb2.PutRequest(key=key, writeType=write_type, fields=field_list, ignoreMemQueueFull=ignore_mem_queue_full,)`. Upsert calls use internally `_prepare_put()` calls.

Side note, upsert calls are different from insert calls only in `writemode`. They can be combined into one.

2024-11-13 21:16 UTC, rahul-aerospike commented on src/aerospike_vector_search/shared/client_helpers.py
> +    ) -> tuple[transact_pb2_grpc.TransactServiceStub, transact_pb2.PutRequest, dict[str, Any]]:
same as above.

2024-11-13 21:24 UTC, rahul-aerospike commented on src/aerospike_vector_search/shared/client_helpers.py
> +    ) -> tuple[transact_pb2_grpc.TransactServiceStub, Any, dict[str, Any]]:
The last dictionary contains the timeout value as of now. Its type internally based on the contents, is dict<str, int>. However, I kept it generic because this dictionary is used to pass ad-hoc parameters to the API across the repository.

In some cases, I noticed that the timeout value is of type int, while in others, it is a float. Everywhere else, the kwargs are defined as dict<str, Any>.

```
        kwargs = {}
        if timeout is not None:
            kwargs["timeout"] = timeout
```

2024-11-13 21:44 UTC, dwelch-spike commented on src/aerospike_vector_search/shared/admin_helpers.py
> +    def _prepare_list_roles(self, timeout: Optional[int], logger: logging.Logger) -> tuple[user_admin_pb2_grpc.UserAdminServiceStub, Any, dict[str, Any]]:
Maybe google.protobuf.empty_pb2.Empty would work? I will try it out when I make the changes for the linter

2024-11-13 21:48 UTC, rahul-aerospike commented on src/aerospike_vector_search/shared/client_helpers.py
> +        record_data: Dict[str, Any],
removed all `Dict` references.

2024-11-13 23:52 UTC, dwelch-spike approved these changes
LGTM, test failures look timing based.

2024-11-14 00:46 UTC, merged