feat: enable toggling index integrity check on index creation and update vec-447
aerospike/avs-client-python pull request #67
Opened 2024-12-06 21:48 UTC by dwelch-spike

2024-12-09 17:35 UTC, DomPeliniAerospike requested changes
Had one question, but looks good otherwise!

2024-12-09 17:35 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +        params.enableVectorIntegrityCheck = self.enable_vector_integrity_check
Should the typehint for this be an optional[bool] rather than just a bool?
It isn't required, because a default is provided if none is given.

2024-12-09 17:37 UTC, DomPeliniAerospike commented on src/aerospike_vector_search/types.py
> +        params.enableVectorIntegrityCheck = self.enable_vector_integrity_check
This comment is in the wrong spot:

It is relating to the typehint for `enable_vector_integrity_check` in `class HnswParams(object):`

2024-12-09 18:58 UTC, dwelch-spike commented on src/aerospike_vector_search/types.py
> +        params.enableVectorIntegrityCheck = self.enable_vector_integrity_check
Made the parameter handle None and changed the type hint and default value.

2024-12-11 18:08 UTC, DomPeliniAerospike approved these changes
Changes look good.  Approved.

2024-12-11 19:45 UTC, merged